export const collectionTypeAction = {
    CREATE_COLLECTION: 'CREATE_COLLECTION',
    FETCH_COLLECTION:   'FETCH_COLLECTION',
    DELETE_COLLECTION: 'DELETE_COLLECTION',
    TOTAL_INCOME: 'TOTAL_INCOME',
    TOTAL_EXPENCES: 'TOTAL_EXPENCES',
    TOTAL_BUDGET: 'TOTAL_BUDGET',
    FETCH_ONE_COLLECTION: 'FETCH_ONE_COLLECTION'
    }